### ISSUE TITLE
Improve equality checking for paths

### ISSUE THREAD

**Issue by janmasrovira** [heliaxdev/minijuvix#169]
Currently to check equality of paths we convert them to absolute paths and check for string equality.
We should use the function [`equalFilePath`](https://hackage.haskell.org/package/filepath-1.4.2.2/docs/System-FilePath.html#v:equalFilePath) and call [`canonicalizePath`](https://hackage.haskell.org/package/directory-1.3.7.0/docs/System-Directory.html#v:canonicalizePath) before that as suggested in the Haskell documentation.

**Comment by jonaprieto** [comment]
Should we use `canonicalizePath` also for example here:

https://github.com/heliaxdev/minijuvix/blob/d1b54befd98e5f60b978faf31e0e892d0885c6f2/app/CLI.hs#L48

**Comment by janmasrovira** [comment]
I think that's a good idea
