### ISSUE TITLE
Missing assets for the HTML generation command

### ISSUE THREAD

**Issue by jonaprieto** [heliaxdev/minijuvix#174]
This blocks https://github.com/heliaxdev/minijuvix-stdlib/pull/1

**Comment by paulcadman** [comment]
One idea is to use file-embed like we did for embedding the C runtime files in the binary. 

https://github.com/heliaxdev/minijuvix/blob/7e71122e7fbcdb368694e3e32e3d3bb27ba2e7da/app/Commands/Compile.hs#L113

The advantage of this approach is that the `html` command could then be used independently of the git checkout.
